In [1]:
import numpy as np

In [3]:
# vamos montar o nosso primeiro array:
a = np.array([2, 3, 5, 7, 11])
a

array([ 2,  3,  5,  7, 11])

In [4]:
# o atributo ndim do array guarda seu número de dimensões
a.ndim

1

In [5]:
# o shape diz o numero de elementos em cada dimensão
a.shape

(5,)

In [6]:
# podemos acessar uma entrada do array
a[2]

5

In [7]:
# tambem podemos alterar uma entrada dele
a[3] = 42
a

array([ 2,  3,  5, 42, 11])

In [12]:
#tudo feito até agora pode-se ser utilizado com qualquer numero de dimensões
#criando uma matriz:
b = np.array([[10, 20], [30, 40], [50, 60]])
b

array([[10, 20],
       [30, 40],
       [50, 60]])

In [13]:
#verificando o shape e numero de dimensões
print(b.ndim)
print(b.shape)

2
(3, 2)


In [15]:
#é preciso informar a posição para acessar elementos (linha, coluna)
b[1, 0] = 23
b


array([[10, 20],
       [23, 40],
       [50, 60]])

In [16]:
#GERANDO ARRAYS
#cria um array só com zeros com shape (2,2)
m = np.zeros((2,2))
print(m)

#cria um array só com com shape (2,2)
n = np.ones((2,2))
print(n)


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [17]:
import random

In [19]:
#cria array de shape (3,2) com valores aleatórios
o = np.random.random((3,2))
print(o)

# cria array com valores aleatórios inteiros 
p = np.random.randint(20, size=(3,2))
print(p)

[[0.33204244 0.91002923]
 [0.07583755 0.02814064]
 [0.09902117 0.37633175]]
[[11 18]
 [15 13]
 [ 1 13]]


In [21]:
# cria vetor de 0 a 4
q = np.arange(4)
print(q)

[0 1 2 3]
